server:
  port: 1111
spring:
  redis:
    host: 192.168.40.130
    port: 6379
    # 数据库索引（默认0）
    database: 0
    password:
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 1s
    # 连接超时时间（毫秒）
    timeout: 5000ms